const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOEUrUjM1bDlaRE1CTStTdGhjREdVeUJPVWJsZjRWelZic0s0NW9TUzFHVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiU2ZhYlAveGxEQnhSUWplM0g4ZzBkTmNLaDY1NStmOVlSUFp3RlZ4SDRGdz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJhQlJwbzhPU1VJQlNKbzhRN3pvQUZCVzhsNVdBY3E1Vm80Z2JhRlNwY25ZPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJVdXR6V0hDUHBpTXdlUVNSaGNFV1J1VFBFN2VBQjN4a2phanJUbnhqSjA4PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlVEWGRUNWdPR1VyaERIc2s4akVJZEdQQUxaSHV0ZTR3dTJlQWlxUjQ0R1U9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Imc1a1BweThVcGpUV2xWTjFuUDIvVFFtR0tYbGJnVjNaQU1zdFNqZkVWbG89In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid043SXpWTlFRSTRFbUtycFVPVmg1S0Z0WjlGbFNXKytwV1pDb2ZoQUNYWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYUtRKzdUeXNxcytLSUx4TU16V2NjaW5qNE9adml2QVFLVUxnQW9MbmJsYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImJYaUtya3NTQUZ1MWYvZHYwTXBzK2pWYllMRmlTdU9wdEdQN1dwUEJQd2NUVlRYNmhBQlYxbDV5SjhZUUt3QVAzcGtpZWdNeTQ3Q1lFMGcvUmU3amlBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjU0LCJhZHZTZWNyZXRLZXkiOiJFWThUbWZrdys4V0JwZTB4RW83MUkvZHNjL3FxbWVOT2daS0JVRzc4TmtnPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI2Mzc3NDU2OTk1N0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIzMDFEM0Y2MEYyRUY2REU0QjcxNTBDODUyMjIwRTVGMiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzQyOTQ5Njg5fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNjM3NzQ1Njk5NTdAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiOEZDQzQ4N0VGQzFBMDNBQjE0QzQ1M0RCRjgzNTQyNkEifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc0Mjk0OTY5MH1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiU0c1MWEtTTZRUkdiMzZtNi1pWnVSUSIsInBob25lSWQiOiI1OGM0YWY3My03NjA3LTQ2OWMtODFkYi05ZjY0NjNhNTJjMGEiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaHZjSVBVVW9rVjBwSDc3RVpZMDRkN1A4OGdFPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImZLRlFYQXdDYnRKeVlTWUJXd1ZyMnZ2MUZNYz0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJQWEgyVllaWSIsIm1lIjp7ImlkIjoiMjYzNzc0NTY5OTU3OjE5QHMud2hhdHNhcHAubmV0IiwibmFtZSI6IkRvY3RvciBCbGVzc2VkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNJRFY0WTBFRUtDYWpiOEdHQUlnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJ0R2U0ZFdhdGpoRi9JZmlNVExwZ0pSczAyaHhETkE1WHlQYjhrSVFaM1ZzPSIsImFjY291bnRTaWduYXR1cmUiOiJHNFc2dmdFT0xnNU1JRnFWT092b3N1aDBQclJDRWw2bHFGckZYSEtRUE9Yd3lTeVdzMlVJY3p4K0Rhckt4eVpjQmxZVkJxdXpyTFIzMW1rQWcwZWtDZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiS1prSzBVelhIOURaQ09ORThNOXpmVmpQZE5hYlNaUzlhMUpmT0J1bDBOOEQ5VnNEMm1EbmlGbDdIdU43UU84b3lsa1RBdXFVMmNyYlkwQlQ2SjlsaVE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNjM3NzQ1Njk5NTc6MTlAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCYlJudUhWbXJZNFJmeUg0akV5NllDVWJOTm9jUXpRT1Y4ajIvSkNFR2QxYiJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc0Mjk0OTY3NywibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFBSTgifQ==",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "263774569957",
  "OWNER_NAME": process.env.OWNER_NAME || "flame",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
