
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSUNybG04QzZZZWRJV1RhdGpHaDNFK3pRT0pWdEVIYzBOcG15K1NCelNWTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUXdYL3d3MXdYcVZIVUcrKzhoWDFjN29PTkVzZ3E1QzRVNmtLSXFBbGpIUT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJJSmhnL3phSTl1WDN5VEloYXFyRzh4dThmeGFBRUFMWUl2NUo2cVJCdTF3PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJUWW1pTWJpRnZ2bzRqaFlFemM4enh3VUc5cnp1Mnc0U1AyWStkTzhVYTE4PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjZIWGZhbjZhR1E2SlJLc1huNUFqN0VDUmRTVWdpUVhIZnphazVsT05rMWc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjFJTXhaNTE4ZVk4d29kU3Uya3lpdFp3ZDBRbktGdFFPTnQxRmk2TmJzaWM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0ZNeXFMc0tKOU9OR0xRRUFlNHA2cTc0SHVtdjVVaDhSdEZ6RDZrdmIxTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUVJybFBEb08rVEQxdDVPWm1ReFRmS25jMTF4YUZjcmo0RndSdVVhK3RFTT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkEwSnNHS0tSV1V1L0xuSnk3MUdxc25icWM5ME55SE53ZVd5SW9mQythYTFnd3Q4S3kxb3hwR2V5bzlRb1lhRUZIQWxSSU1GckZWL0VDVTlPVEpzbWh3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6OTksImFkdlNlY3JldEtleSI6IlBvSy9jdS9WZXRVMjVKZ3E2Z0RYTzRmMEJhcXlpZEsyaUQrRElkZXZmd2M9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6InQ4UFlvZTRoVEx5T0tiZUJ0MHhZTFEiLCJwaG9uZUlkIjoiODM5ODUyNzEtODY2Ny00ZTU1LWI0ODUtNmFjNDZkNTU3Yzc3IiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InRFL2kwczJNOWUwam5DSmMrWTVKRWRGcVdlOD0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI3M1pkeDEvS1h5ejY5cURzWUx5SE56d0Vnajg9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiV1ZEVjRYNDUiLCJtZSI6eyJpZCI6IjI2Mzc3NDU2OTk1NzoyNEBzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDSURWNFkwRUVNUHdsNzhHR0FjZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoidEdlNGRXYXRqaEYvSWZpTVRMcGdKUnMwMmh4RE5BNVh5UGI4a0lRWjNWcz0iLCJhY2NvdW50U2lnbmF0dXJlIjoidzJmeWZaTXlteEErV3MydDdzYWV3bjExMXVpUUtBN3I1ME5KekhRVmIyY21QeHU5VHdOcGtGcXVuKzFmL0RQRGlDMlBIN2psVndJQVd2VnY2THJGRGc9PSIsImRldmljZVNpZ25hdHVyZSI6IkVpcFA0dDlPNHNxTGhhSGVyL0VsNC8xSzNlR3ArRHZJVzBMdDUvT3NMcGxxTzJjOWFoTDVQRkJ3d1Z2TmdXNU5XZlJoc216VVE1ZnZIdEFDQWJna2dRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjYzNzc0NTY5OTU3OjI0QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmJSbnVIVm1yWTRSZnlINGpFeTZZQ1ViTk5vY1F6UU9WOGoyL0pDRUdkMWIifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NDMxMjQ1NjAsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBQUk4In0=",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "263774569957",
  "OWNER_NAME": process.env.OWNER_NAME || "flame",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "263774569957",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
